[project]
name = 'smart-wallet'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ext-delegate-stx-pox-4]
path = 'contracts/ext-delegate-stx-pox-4.clar'
clarity_version = 3
epoch = 3.1

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.pox-4]
path = 'contracts/pox-4.clar'
clarity_version = 3
epoch = 3.1

[contracts.smart-wallet]
path = 'contracts/smart-wallet.clar'
clarity_version = 3
epoch = 3.1

[contracts.smart-wallet-trait]
path = 'contracts/smart-wallet-trait.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
