[project]
name = 'Smart-Wallet'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.nope'

[[project.requirements]]
contract_id = 'SP16GEW6P7GBGZG0PXRXFJEMR3TJHJEY2HJKBP1P5.og-bitcoin-pizza-leather-edition'
[contracts.emergency-rules]
path = 'contracts/rules/emergency-rules.clar'
clarity_version = 2
epoch = 2.1

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.inactive-observer]
path = 'contracts/admins/inactive-observer.clar'
clarity_version = 2
epoch = 2.1

[contracts.no-rules]
path = 'contracts/rules/no-rules.clar'
clarity_version = 2
epoch = 2.1

[contracts.rule-set-trait]
path = 'contracts/rule-set-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet]
path = 'contracts/smart-wallet.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-endpoint]
path = 'contracts/smart-wallet-endpoint.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-standard]
path = 'contracts/smart-wallet-standard.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-trait]
path = 'contracts/smart-wallet-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.sponsored-transfer]
path = 'contracts/extensions/sponsored-transfer.clar'
clarity_version = 2
epoch = 2.1

[contracts.standard-rules]
path = 'contracts/rules/standard-rules.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
