[project]
name = 'Smart-Wallet'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'


requirements = [
    { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" },
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait" },
    { contract_id = "SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-semi-fungible-token-trait" },
    { contract_id = "SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin" },
    { contract_id = "SP16GEW6P7GBGZG0PXRXFJEMR3TJHJEY2HJKBP1P5.og-bitcoin-pizza-leather-edition" },
    { contract_id = "SP000000000000000000002Q6VF78.pox-4" },
    { contract_id = "SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.nope" },
]


[contracts.emergency-rules]
path = 'contracts/rules/emergency-rules.clar'
clarity_version = 2
epoch = 2.1

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.inactive-observer]
path = 'contracts/admins/inactive-observer.clar'
clarity_version = 2
epoch = 2.1

[contracts.no-rules]
path = 'contracts/rules/no-rules.clar'
clarity_version = 2
epoch = 2.1

[contracts.rule-set-trait]
path = 'contracts/rule-set-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet]
path = 'contracts/smart-wallet.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-endpoint]
path = 'contracts/smart-wallet-endpoint.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-standard]
path = 'contracts/smart-wallet-standard.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-standard-endpoint]
path = 'contracts/smart-wallet-standard-endpoint.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet-trait]
path = 'contracts/smart-wallet-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.standard-rules]
path = 'contracts/rules/standard-rules.clar'
clarity_version = 2
epoch = 2.1

[contracts.ext-sponsored-transfer]
path = 'contracts/extensions/ext-sponsored-transfer.clar'
clarity_version = 2
epoch = 2.1


[contracts.ext-delegate-stx-pox-4]
path = 'contracts/extensions/ext-delegate-stx-pox-4.clar'
clarity_version = 2
epoch = 2.5

[contracts.ext-test]
path = 'contracts/tests/ext-test.clar'
clarity_version = 2
epoch = 2.5
