[project]
name = 'Smart-Wallet'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.lisa-dao]
path = 'contracts/lisa-dao.clar'
clarity_version = 2
epoch = 2.1

[contracts.smart-wallet]
path = 'contracts/smart-wallet.clar'
depends_on = ["lisa-dao"]
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
